# SHOW INDEX FROM questions_mc;

ALTER TABLE questions    ENGINE=InnoDB;
ALTER TABLE questions_m  ENGINE=InnoDB;
ALTER TABLE questions_mc ENGINE=InnoDB;
ALTER TABLE questions_c  ENGINE=InnoDB;
ALTER TABLE questions_p  ENGINE=InnoDB;
ALTER TABLE questions_s  ENGINE=InnoDB;
ALTER TABLE images 		 ENGINE=InnoDB;
ALTER TABLE questions ADD FOREIGN KEY (`images_id`) REFERENCES `images` (`id`);
ALTER TABLE questions DROP image;
ALTER TABLE questions CHANGE answers_config answersConfig INTEGER;
ALTER TABLE questions CHANGE question_config questionConfig INTEGER;
ALTER TABLE questions_mc MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_mc MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_mc DROP FOREIGN KEY questions_mc_ibfk_1;
ALTER TABLE questions_mc CHANGE id questions_id INTEGER;
ALTER TABLE questions_mc ADD FOREIGN KEY (`questions_id`) REFERENCES `questions` (`id`);
ALTER TABLE questions_mc MODIFY image1 INT DEFAULT NULL;
UPDATE questions_mc SET image1=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image1`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image2 INT DEFAULT NULL;
UPDATE questions_mc SET image2=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image2`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image3 INT DEFAULT NULL;
UPDATE questions_mc SET image3=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image3`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image4 INT DEFAULT NULL;
UPDATE questions_mc SET image4=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image4`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image5 INT DEFAULT NULL;
UPDATE questions_mc SET image5=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image5`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image6 INT DEFAULT NULL;
UPDATE questions_mc SET image6=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image6`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image7 INT DEFAULT NULL;
UPDATE questions_mc SET image7=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image7`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image8 INT DEFAULT NULL;
UPDATE questions_mc SET image8=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image8`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image9 INT DEFAULT NULL;
UPDATE questions_mc SET image9=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image9`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image10 INT DEFAULT NULL;
UPDATE questions_mc SET image10=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image10`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image11 INT DEFAULT NULL;
UPDATE questions_mc SET image11=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image11`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image12 INT DEFAULT NULL;
UPDATE questions_mc SET image12=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image12`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image13 INT DEFAULT NULL;
UPDATE questions_mc SET image13=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image13`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image14 INT DEFAULT NULL;
UPDATE questions_mc SET image14=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image14`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image15 INT DEFAULT NULL;
UPDATE questions_mc SET image15=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image15`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image16 INT DEFAULT NULL;
UPDATE questions_mc SET image16=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image16`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image17 INT DEFAULT NULL;
UPDATE questions_mc SET image17=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image17`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image18 INT DEFAULT NULL;
UPDATE questions_mc SET image18=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image18`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image19 INT DEFAULT NULL;
UPDATE questions_mc SET image19=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image19`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image20 INT DEFAULT NULL;
UPDATE questions_mc SET image20=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image20`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image21 INT DEFAULT NULL;
UPDATE questions_mc SET image21=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image21`) REFERENCES `images` (`id`);
ALTER TABLE questions_mc MODIFY image22 INT DEFAULT NULL;
UPDATE questions_mc SET image22=NULL;
ALTER TABLE questions_mc ADD FOREIGN KEY (`image22`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_m DROP FOREIGN KEY questions_m_ibfk_1;
ALTER TABLE questions_m CHANGE id questions_id INTEGER;
ALTER TABLE questions_m ADD FOREIGN KEY (`questions_id`) REFERENCES `questions` (`id`);
ALTER TABLE questions_m MODIFY Limage1 INT DEFAULT NULL;
UPDATE questions_m SET Limage1=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage1`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage1 INT DEFAULT NULL;
UPDATE questions_m SET Rimage1=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage1`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage2 INT DEFAULT NULL;
UPDATE questions_m SET Limage2=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage2`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage2 INT DEFAULT NULL;
UPDATE questions_m SET Rimage2=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage2`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage3 INT DEFAULT NULL;
UPDATE questions_m SET Limage3=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage3`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage3 INT DEFAULT NULL;
UPDATE questions_m SET Rimage3=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage3`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage4 INT DEFAULT NULL;
UPDATE questions_m SET Limage4=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage4`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage4 INT DEFAULT NULL;
UPDATE questions_m SET Rimage4=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage4`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage5 INT DEFAULT NULL;
UPDATE questions_m SET Limage5=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage5`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage5 INT DEFAULT NULL;
UPDATE questions_m SET Rimage5=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage5`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage6 INT DEFAULT NULL;
UPDATE questions_m SET Limage6=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage6`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage6 INT DEFAULT NULL;
UPDATE questions_m SET Rimage6=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage6`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage7 INT DEFAULT NULL;
UPDATE questions_m SET Limage7=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage7`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage7 INT DEFAULT NULL;
UPDATE questions_m SET Rimage7=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage7`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage8 INT DEFAULT NULL;
UPDATE questions_m SET Limage8=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage8`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage8 INT DEFAULT NULL;
UPDATE questions_m SET Rimage8=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage8`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage9 INT DEFAULT NULL;
UPDATE questions_m SET Limage9=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage9`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage9 INT DEFAULT NULL;
UPDATE questions_m SET Rimage9=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage9`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage10 INT DEFAULT NULL;
UPDATE questions_m SET Limage10=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage10`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage10 INT DEFAULT NULL;
UPDATE questions_m SET Rimage10=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage10`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage11 INT DEFAULT NULL;
UPDATE questions_m SET Limage11=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage11`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage11 INT DEFAULT NULL;
UPDATE questions_m SET Rimage11=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage11`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage12 INT DEFAULT NULL;
UPDATE questions_m SET Limage12=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage12`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage12 INT DEFAULT NULL;
UPDATE questions_m SET Rimage12=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage12`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage13 INT DEFAULT NULL;
UPDATE questions_m SET Limage13=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage13`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage13 INT DEFAULT NULL;
UPDATE questions_m SET Rimage13=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage13`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage14 INT DEFAULT NULL;
UPDATE questions_m SET Limage14=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage14`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage14 INT DEFAULT NULL;
UPDATE questions_m SET Rimage14=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage14`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage15 INT DEFAULT NULL;
UPDATE questions_m SET Limage15=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage15`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage15 INT DEFAULT NULL;
UPDATE questions_m SET Rimage15=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage15`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage16 INT DEFAULT NULL;
UPDATE questions_m SET Limage16=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage16`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage16 INT DEFAULT NULL;
UPDATE questions_m SET Rimage16=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage16`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage17 INT DEFAULT NULL;
UPDATE questions_m SET Limage17=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage17`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage17 INT DEFAULT NULL;
UPDATE questions_m SET Rimage17=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage17`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage18 INT DEFAULT NULL;
UPDATE questions_m SET Limage18=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage18`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage18 INT DEFAULT NULL;
UPDATE questions_m SET Rimage18=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage18`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage19 INT DEFAULT NULL;
UPDATE questions_m SET Limage19=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage19`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage19 INT DEFAULT NULL;
UPDATE questions_m SET Rimage19=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage19`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage20 INT DEFAULT NULL;
UPDATE questions_m SET Limage20=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage20`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage20 INT DEFAULT NULL;
UPDATE questions_m SET Rimage20=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage20`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage21 INT DEFAULT NULL;
UPDATE questions_m SET Limage21=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage21`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage21 INT DEFAULT NULL;
UPDATE questions_m SET Rimage21=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage21`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage22 INT DEFAULT NULL;
UPDATE questions_m SET Limage22=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage22`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage22 INT DEFAULT NULL;
UPDATE questions_m SET Rimage22=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage22`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage23 INT DEFAULT NULL;
UPDATE questions_m SET Limage23=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage23`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage23 INT DEFAULT NULL;
UPDATE questions_m SET Rimage23=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage23`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage24 INT DEFAULT NULL;
UPDATE questions_m SET Limage24=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage24`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage24 INT DEFAULT NULL;
UPDATE questions_m SET Rimage24=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage24`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage25 INT DEFAULT NULL;
UPDATE questions_m SET Limage25=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage25`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage25 INT DEFAULT NULL;
UPDATE questions_m SET Rimage25=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage25`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage26 INT DEFAULT NULL;
UPDATE questions_m SET Limage26=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage26`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage26 INT DEFAULT NULL;
UPDATE questions_m SET Rimage26=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage26`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Limage27 INT DEFAULT NULL;
UPDATE questions_m SET Limage27=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Limage27`) REFERENCES `images` (`id`);
ALTER TABLE questions_m MODIFY Rimage27 INT DEFAULT NULL;
UPDATE questions_m SET Rimage27=NULL;
ALTER TABLE questions_m ADD FOREIGN KEY (`Rimage27`) REFERENCES `images` (`id`);
ALTER TABLE questions_c MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_c DROP FOREIGN KEY questions_c_ibfk_1;
ALTER TABLE questions_c CHANGE id questions_id INTEGER;
ALTER TABLE questions_c ADD FOREIGN KEY (`questions_id`) REFERENCES `questions` (`id`);
ALTER TABLE questions_p MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_p DROP FOREIGN KEY questions_p_ibfk_1;
ALTER TABLE questions_p CHANGE id questions_id INTEGER;
ALTER TABLE questions_p ADD FOREIGN KEY (`questions_id`) REFERENCES `questions` (`id`);
ALTER TABLE questions_s MODIFY id INT DEFAULT NULL;
ALTER TABLE questions_s DROP FOREIGN KEY questions_s_ibfk_1;
ALTER TABLE questions_s CHANGE id questions_id INTEGER;
ALTER TABLE questions_s ADD FOREIGN KEY (`questions_id`) REFERENCES `questions` (`id`);
ALTER TABLE questions ADD author int(11) NOT NULL;
ALTER TABLE questions ADD verified int(1) NOT NULL DEFAULT '0';
ALTER TABLE questions ADD verified_by int(11) NOT NULL;
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN1$|PreLab01$|Lab1$|Chapter1$|-Mod1$|Complex$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN2$|PreLab02$|Lab2$|Chapter2$|-Mod2$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN3$|PreLab03$|Lab3$|Chapter3$|-Mod3$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN4$|PreLab04$|Lab4$|Chapter4$|-Mod4$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN5$|PreLab05$|Lab5$|Chapter5$|-Mod5$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN6$|PreLab06$|Lab6$|Chapter6$|-Mod6$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN7$|PreLab07$|Lab7$|Chapter7$|-Mod7$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN8$|PreLab08$|Lab8$|Chapter8$|-Mod8$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN9$|PreLab09$|Lab9$|Chapter9$|-Mod9$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN10$|PreLab010$|Lab10$|Chapter10$|-Mod10$)" AND qtype IN ("MC","M","C");
UPDATE questions SET verified=1 WHERE category REGEXP "(SPEN11$|PreLab011$|Lab11$|Chapter11$|-Mod11$)" AND qtype IN ("MC","M","C");
